---
dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  # Use `cspell-cli trace word` to check where a work is defined
  - en_US
  - bash
  - words
  - python
  - "!backwards-compatibility"
  - "!cryptocurrencies"
  - "!cpp"
enabled: true
useGitignore: true
ignorePaths:
  - "**/*-artifact-*.json"
  - "*.svg"
  - ./vscode-ansible.Containerfile
  - .tekton/
  - .yarn/
  - dist/
  - media
  - out/
  - package.json
  - syntaxes
  - syntaxes/external/*.*
  - test/testFixtures/lightspeed/*.yml
  - tsconfig*.json
  - uv.lock
ignoreRegExpList:
  # ignore github usernames like @foo
  - "@[\\w]+"
  # ignore usernames in vscode settings paths
  - "/Users/[\\w]+/"
