---
dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  # Use `cspell-cli trace word` to check where a work is defined
  - en_US
  - bash
  - words
  - python
  - "!backwards-compatibility"
  - "!cryptocurrencies"
  - "!cpp"
ignorePaths:
  - docs/requirements.in
  - docs/requirements.txt
  - requirements.txt
