---
dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  # Use `cspell-cli trace word` to check where a work is defined
  - en_US
  - bash
  - words
  - python
  - "!backwards-compatibility"
  - "!cryptocurrencies"
  - "!cpp"
ignorePaths:
  - "**/requirements.in"
  - .config/constraints.txt
  - .yarn/
  - media
  - package.json
  - syntaxes
  - syntaxes/external/*.*
  - test/testFixtures/lightspeed/*.yml
  - .tekton/
  - ./vscode-ansible.Containerfile
ignoreRegExpList:
  # ignore github usernames like @foo
  - "@[\\w]+"
  # ignore usernames in vscode settings paths
  - "/Users/[\\w]+/"
