version: 3
dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
images:
  base_image:
    name: quay.io/fedora/fedora:41
options:
  tags:
    - ansible_sample_ee
  package_manager_path: /usr/bin/dnf5
additional_build_steps:
  prepend_base:
    - RUN $PKGMGR -y -q install python3-devel
