name: builder
on:
  push:
    branches:
      - main
      - "releases/**"
      - "stable/**"
    paths: &paths
      - .config/mise*.toml
      - .pre-commit-config.yaml
      - .python-version
      - Containerfile
      - package*.json
      - pyproject.toml
      - tools/builder.sh
      - uv.lock
  pull_request:
    types: [synchronize, opened, reopened]
    branches: ["main", "devel/*"]
    paths: *paths
jobs:
  builder-image:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./tools/builder.sh ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && '--push' || '' }}
